### PR TITLE
MNT/REF/BLD: apply python cookiecutter to repository

### PR DESCRIPTION
**Pull request by tangkong**
This one's a doozy.  It's tough to parse the diff but to the best of my ability I've:

- added github workflows
- added github PR, issue templates
- added packaging boilerplate (conda, pip)
- added our standard docs framework
- moved the tests inside the inner `beams` folder, as is the norm for our packages

This will probably take a revision or two as CI starts up and i realize exactly what I've missed

Follow-ups for later PRs:
- PEP8 style related fixes
- add beams/bin cli entrypoint
- rename TestFiles.py to test_files.py and adjust makefile to let pytest auto-detect

### CODE REVIEW

**Comment by tangkong** [comment]
Thanks for the fixups Josh!  Any objections before I merge this and make some followups?  I sort of expect this to break in CI for a bit but I'll focus on resolving those issues asap

**Review by ZLLentz — APPROVED** [review]
fwiw I read through this and didn't notice any glaring issues

**Comment by joshc-slac** [comment]
No problem. Thanks for LCLS-ifying this code base it was in dire need. I was waiting on file name changes (there's a chance that's breaking to our current testing schema) pre approve but I'll approve this and we can include that in another PR should one of us feel the urge to take a pass.

**Review by joshc-slac — APPROVED** [review]

**Comment by tangkong** [comment]
I think the getting the test suite working in ci will take a bit of work, involving both changing filenames and pytest-ing the test IOCs.  That's the main reason I delayed that fixup

**Pull request merged**
