### PR TITLE
FIX: race condition in test worker made it conditional on hardware speed

### LINKED ISSUE #27: BUG/CI: inconsistent Worker behavior in CI
## Current Behavior
Something about multiprocessing and passing values

https://github.com/pcdshub/BEAMS/actions/runs/10270927493/job/28419770161?pr=26#step:14:62

## Expected Behavior
Every run should be consistent

## Context / environment
#26 

## Steps to Reproduce (for bugs)
1. Run CI
2. Run CI again

## Suggested Solution
??

### PR DESCRIPTION
**Pull request by joshc-slac**
Closes #27 
## Description
There was a fun bug in our Worker class tests that made success conditional (or downright non deterministic) on hardware it was run on. Centered around this condition:

https://github.com/pcdshub/BEAMS/blob/4be9dc569c857e275fe573ea19e35b926ec358a1/beams/tests/test_worker.py#L28-L29

This was intended to have the logic:
> Keep work thread alive until stop work signal is sent *and* the logical task is completed

The issue being with being with no sleep in the work function on sufficiently fast hardware or with a significantly long wait for whatever reason between these two lines: https://github.com/pcdshub/BEAMS/blob/4be9dc569c857e275fe573ea19e35b926ec358a1/beams/tests/test_worker.py#L32-L33

It could count up very high as seen [here](https://github.com/pcdshub/BEAMS/actions/runs/10270927493/job/28419770161?pr=26#step:14:62)

The simple solution was adding a logic gate to incrementing the checking value. 

**Note:** There are many other solutions that might be more performant; we should benchmark in python and standardize to make sure the busy waiting / no load threads are not locking out OS. I would be surprised if python doesn't handle this for us. I miss C. 

## Motivation and Context
I want to standardize how 'work' is done for a few reasons enumerated here: #28. While this shows the issue was not in fact in our Worker declaration hopefully this PR serves as a sign post to future developers and is scaffolding for however we decide to standardize work function generation. 

Additionally  we need our tests to pass deterministically. 

## How Has This Been Tested?
In our unit tests

## Pre-merge checklist

- [ ] Code works interactively
- [ ] Code follows the [style guide](https://pcdshub.github.io/style.html)
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on GitHub Actions
- [ ] Ran ``docs/pre-release-notes.sh`` and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
Good practical fix that makes the test slightly more like a real thing

**Review by tangkong — APPROVED** [review]
I think I was also running into this in reworking the tests to fit the new serialization schemes.

**Comment by tangkong** [comment]
Oh also pre-release notes

**Comment by joshc-slac** [comment]
> Oh also pre-release notes

deal deal, mentally told myself to do it but then forgot my b

**Pull request merged**
